# FIX Protocol (Financial Information eXchange) Parser
# Common FIX tags and message types for decoding

# FIX Message Types (Tag 35)
MESSAGE_TYPES = {
    '0': 'Heartbeat',
    '1': 'Test Request',
    '2': 'Resend Request',
    '3': 'Reject',
    '4': 'Sequence Reset',
    '5': 'Logout',
    '8': 'Execution Report',
    '9': 'Order Cancel Reject',
    'A': 'Logon',
    'D': 'New Order Single',
    'E': 'New Order List',
    'F': 'Order Cancel Request',
    'G': 'Order Cancel/Replace Request',
    'H': 'Order Status Request',
    'J': 'Allocation Instruction',
    'K': 'List Cancel Request',
    'L': 'List Execute',
    'M': 'List Status Request',
    'N': 'List Status',
    'P': 'Allocation Instruction Ack',
    'Q': 'Don\'t Know Trade',
    'R': 'Quote Request',
    'S': 'Quote',
    'T': 'Settlement Instructions',
    'V': 'Market Data Request',
    'W': 'Market Data Snapshot',
    'X': 'Market Data Incremental Refresh',
    'Y': 'Market Data Request Reject',
    'Z': 'Quote Cancel',
    'AA': 'Quote Status Request',
    'AB': 'Mass Quote Acknowledgement',
    'AC': 'Security Definition Request',
    'AD': 'Security Definition',
    'AE': 'Trade Capture Report',
    'AF': 'Order Mass Cancel Request',
    'AG': 'Order Mass Cancel Report',
    'AH': 'Position Maintenance Request',
    'AI': 'Position Maintenance Report',
    'AJ': 'Position Report',
    'AK': 'Trade Capture Report Request Ack',
    'AL': 'Trade Capture Report Ack',
    'AN': 'Collateral Request',
    'AO': 'Collateral Assignment',
}

# Common FIX Tags
TAG_NAMES = {
    '1': 'Account',
    '6': 'AvgPx',
    '7': 'BeginSeqNo',
    '8': 'BeginString',
    '9': 'BodyLength',
    '10': 'CheckSum',
    '11': 'ClOrdID',
    '14': 'CumQty',
    '15': 'Currency',
    '16': 'EndSeqNo',
    '17': 'ExecID',
    '18': 'ExecInst',
    '19': 'ExecRefID',
    '20': 'ExecTransType',
    '21': 'HandlInst',
    '22': 'SecurityIDSource',
    '31': 'LastPx',
    '32': 'LastQty',
    '34': 'MsgSeqNum',
    '35': 'MsgType',
    '36': 'NewSeqNo',
    '37': 'OrderID',
    '38': 'OrderQty',
    '39': 'OrdStatus',
    '40': 'OrdType',
    '41': 'OrigClOrdID',
    '43': 'PossDupFlag',
    '44': 'Price',
    '45': 'RefSeqNum',
    '48': 'SecurityID',
    '49': 'SenderCompID',
    '50': 'SenderSubID',
    '52': 'SendingTime',
    '54': 'Side',
    '55': 'Symbol',
    '56': 'TargetCompID',
    '57': 'TargetSubID',
    '58': 'Text',
    '59': 'TimeInForce',
    '60': 'TransactTime',
    '63': 'SettlType',
    '64': 'SettlDate',
    '75': 'TradeDate',
    '76': 'ExecBroker',
    '77': 'PositionEffect',
    '78': 'NoAllocs',
    '79': 'AllocAccount',
    '97': 'PossResend',
    '98': 'EncryptMethod',
    '99': 'StopPx',
    '100': 'ExDestination',
    '102': 'CxlRejReason',
    '103': 'OrdRejReason',
    '108': 'HeartBtInt',
    '109': 'ClientID',
    '110': 'MinQty',
    '111': 'MaxFloor',
    '112': 'TestReqID',
    '115': 'OnBehalfOfCompID',
    '122': 'OrigSendingTime',
    '123': 'GapFillFlag',
    '126': 'ExpireTime',
    '127': 'DKReason',
    '128': 'DeliverToCompID',
    '129': 'DeliverToSubID',
    '130': 'IOINaturalFlag',
    '131': 'QuoteReqID',
    '132': 'BidPx',
    '133': 'OfferPx',
    '134': 'BidSize',
    '135': 'OfferSize',
    '136': 'NoMiscFees',
    '137': 'MiscFeeAmt',
    '138': 'MiscFeeCurr',
    '139': 'MiscFeeType',
    '140': 'PrevClosePx',
    '141': 'ResetSeqNumFlag',
    '142': 'SenderLocationID',
    '143': 'TargetLocationID',
    '144': 'OnBehalfOfLocationID',
    '145': 'DeliverToLocationID',
    '146': 'NoRelatedSym',
    '150': 'ExecType',
    '151': 'LeavesQty',
    '152': 'CashOrderQty',
    '153': 'AllocAvgPx',
    '154': 'AllocNetMoney',
    '155': 'SettlCurrFxRate',
    '156': 'SettlCurrFxRateCalc',
    '157': 'NumDaysInterest',
    '158': 'AccruedInterestRate',
    '159': 'AccruedInterestAmt',
    '160': 'SettlInstMode',
    '161': 'AllocText',
    '162': 'SettlInstID',
    '163': 'SettlInstTransType',
    '164': 'EmailThreadID',
    '165': 'SettlInstSource',
    '167': 'SecurityType',
    '168': 'EffectiveTime',
    '169': 'StandInstDbType',
    '170': 'StandInstDbName',
    '171': 'StandInstDbID',
    '172': 'SettlDeliveryType',
    '188': 'BidSpotRate',
    '189': 'BidForwardPoints',
    '190': 'OfferSpotRate',
    '191': 'OfferForwardPoints',
    '192': 'OrderQty2',
    '193': 'SettlDate2',
    '194': 'LastSpotRate',
    '195': 'LastForwardPoints',
    '196': 'AllocLinkID',
    '197': 'AllocLinkType',
    '198': 'SecondaryOrderID',
    '199': 'NoIOIQualifiers',
    '200': 'MaturityMonthYear',
    '201': 'PutOrCall',
    '202': 'StrikePrice',
    '203': 'CoveredOrUncovered',
    '204': 'CustomerOrFirm',
    '205': 'MaturityDay',
    '206': 'OptAttribute',
    '207': 'SecurityExchange',
    '208': 'NotifyBrokerOfCredit',
    '209': 'AllocHandlInst',
    '210': 'MaxShow',
    '211': 'PegOffsetValue',
    '262': 'MDReqID',
    '263': 'SubscriptionRequestType',
    '264': 'MarketDepth',
    '265': 'MDUpdateType',
    '266': 'AggregatedBook',
    '267': 'NoMDEntryTypes',
    '268': 'NoMDEntries',
    '269': 'MDEntryType',
    '270': 'MDEntryPx',
    '271': 'MDEntrySize',
    '272': 'MDEntryDate',
    '273': 'MDEntryTime',
    '274': 'TickDirection',
    '275': 'MDMkt',
    '276': 'QuoteCondition',
    '277': 'TradeCondition',
    '278': 'MDEntryID',
    '279': 'MDUpdateAction',
    '280': 'MDEntryRefID',
    '281': 'MDReqRejReason',
    '282': 'MDEntryOriginator',
    '283': 'LocationID',
    '284': 'DeskID',
    '285': 'DeleteReason',
    '286': 'OpenCloseSettlFlag',
    '287': 'SellerDays',
    '288': 'MDEntryBuyer',
    '289': 'MDEntrySeller',
    '290': 'MDEntryPositionNo',
    '291': 'FinancialStatus',
    '292': 'CorporateAction',
    '293': 'DefBidSize',
    '294': 'DefOfferSize',
    '295': 'NoQuoteEntries',
    '296': 'NoQuoteSets',
    '297': 'QuoteStatus',
    '298': 'QuoteCancelType',
    '299': 'QuoteEntryID',
    '300': 'QuoteRejectReason',
    '301': 'QuoteResponseLevel',
    '302': 'QuoteSetID',
    '303': 'QuoteRequestType',
    '304': 'TotNoQuoteEntries',
    '305': 'UnderlyingSecurityIDSource',
    '306': 'UnderlyingIssuer',
    '307': 'UnderlyingSecurityDesc',
    '308': 'UnderlyingSecurityExchange',
    '309': 'UnderlyingSecurityID',
    '310': 'UnderlyingSecurityType',
    '311': 'UnderlyingSymbol',
    '312': 'UnderlyingSymbolSfx',
    '313': 'UnderlyingMaturityMonthYear',
    '314': 'UnderlyingMaturityDay',
    '315': 'UnderlyingPutOrCall',
    '316': 'UnderlyingStrikePrice',
    '317': 'UnderlyingOptAttribute',
    '318': 'UnderlyingCurrency',
    '319': 'RatioQty',
    '320': 'SecurityReqID',
    '321': 'SecurityRequestType',
    '322': 'SecurityResponseID',
    '323': 'SecurityResponseType',
    '324': 'SecurityStatusReqID',
    '325': 'UnsolicitedIndicator',
    '326': 'SecurityTradingStatus',
    '327': 'HaltReason',
    '328': 'InViewOfCommon',
    '329': 'DueToRelated',
    '330': 'BuyVolume',
    '331': 'SellVolume',
    '332': 'HighPx',
    '333': 'LowPx',
    '334': 'Adjustment',
    '335': 'TradSesReqID',
    '336': 'TradingSessionID',
    '337': 'ContraTrader',
    '338': 'TradSesMethod',
    '339': 'TradSesMode',
    '340': 'TradSesStatus',
    '341': 'TradSesStartTime',
    '342': 'TradSesOpenTime',
    '343': 'TradSesPreCloseTime',
    '344': 'TradSesCloseTime',
    '345': 'TradSesEndTime',
    '346': 'NumberOfOrders',
    '347': 'MessageEncoding',
    '371': 'RefTagID',
    '372': 'RefMsgType',
    '373': 'SessionRejectReason',
    '374': 'BidRequestTransType',
    '375': 'ContraBroker',
    '376': 'ComplianceID',
    '377': 'SolicitedFlag',
    '378': 'ExecRestatementReason',
    '379': 'BusinessRejectRefID',
    '380': 'BusinessRejectReason',
    '381': 'GrossTradeAmt',
    '382': 'NoContraBrokers',
    '383': 'MaxMessageSize',
    '384': 'NoMsgTypes',
    '385': 'MsgDirection',
    '386': 'NoTradingSessions',
    '387': 'TotalVolumeTraded',
    '388': 'DiscretionInst',
    '389': 'DiscretionOffsetValue',
    '390': 'BidID',
    '391': 'ClientBidID',
    '392': 'ListName',
    '393': 'TotNoRelatedSym',
    '394': 'BidType',
    '395': 'NumTickets',
    '396': 'SideValue1',
    '397': 'SideValue2',
    '398': 'NoBidDescriptors',
    '399': 'BidDescriptorType',
    '400': 'BidDescriptor',
    '401': 'SideValueInd',
    '402': 'LiquidityPctLow',
    '403': 'LiquidityPctHigh',
    '404': 'LiquidityValue',
    '405': 'EFPTrackingError',
    '406': 'FairValue',
    '407': 'OutsideIndexPct',
    '408': 'ValueOfFutures',
    '409': 'LiquidityIndType',
    '410': 'WtAverageLiquidity',
    '411': 'ExchangeForPhysical',
    '412': 'OutMainCntryUIndex',
    '413': 'CrossPercent',
    '414': 'ProgRptReqs',
    '415': 'ProgPeriodInterval',
    '416': 'IncTaxInd',
    '417': 'NumBidders',
    '418': 'BidTradeType',
    '419': 'BasisPxType',
    '420': 'NoBidComponents',
    '421': 'Country',
    '422': 'TotNoStrikes',
    '423': 'PriceType',
    '424': 'DayOrderQty',
    '425': 'DayCumQty',
    '426': 'DayAvgPx',
    '427': 'GTBookingInst',
    '428': 'NoStrikes',
    '429': 'ListStatusType',
    '430': 'NetGrossInd',
    '431': 'ListOrderStatus',
    '432': 'ExpireDate',
    '433': 'ListExecInstType',
    '434': 'CxlRejResponseTo',
    '435': 'UnderlyingCouponRate',
    '436': 'UnderlyingContractMultiplier',
    '437': 'ContraTradeQty',
    '438': 'ContraTradeTime',
    '439': 'ClearingFirm',
    '440': 'ClearingAccount',
    '441': 'LiquidityNumSecurities',
    '442': 'MultiLegReportingType',
    '443': 'StrikeTime',
    '444': 'ListStatusText',
    '445': 'EncodedListStatusTextLen',
    '446': 'EncodedListStatusText',
    '447': 'PartyIDSource',
    '448': 'PartyID',
    '449': 'TotalVolumeTradedDate',
    '450': 'TotalVolumeTradedTime',
    '451': 'NetChgPrevDay',
    '452': 'PartyRole',
    '453': 'NoPartyIDs',
    '454': 'NoSecurityAltID',
    '455': 'SecurityAltID',
    '456': 'SecurityAltIDSource',
    '457': 'NoUnderlyingSecurityAltID',
    '458': 'UnderlyingSecurityAltID',
    '459': 'UnderlyingSecurityAltIDSource',
    '460': 'Product',
    '461': 'CFICode',
    '462': 'UnderlyingProduct',
    '463': 'UnderlyingCFICode',
    '464': 'TestMessageIndicator',
    '465': 'QuantityType',
    '466': 'BookingRefID',
    '467': 'IndividualAllocID',
    '468': 'RoundingDirection',
    '469': 'RoundingModulus',
    '470': 'CountryOfIssue',
    '471': 'StateOrProvinceOfIssue',
    '472': 'LocaleOfIssue',
    '473': 'NoRegistDtls',
    '474': 'MailingDtls',
    '475': 'InvestorCountryOfResidence',
    '476': 'PaymentRef',
    '477': 'DistribPaymentMethod',
    '478': 'CashDistribCurr',
    '479': 'CommCurrency',
    '480': 'CancellationRights',
    '481': 'MoneyLaunderingStatus',
    '482': 'MailingInst',
    '483': 'TransBkdTime',
    '484': 'ExecPriceType',
    '485': 'ExecPriceAdjustment',
    '486': 'DateOfBirth',
    '487': 'TradeReportTransType',
    '488': 'CardHolderName',
    '489': 'CardNumber',
    '490': 'CardExpDate',
    '491': 'CardIssNum',
    '492': 'PaymentMethod',
    '493': 'RegistAcctType',
    '494': 'Designation',
    '495': 'TaxAdvantageType',
    '496': 'RegistRejReasonText',
    '497': 'FundRenewWaiv',
    '498': 'CashDistribAgentName',
    '499': 'CashDistribAgentCode',
    '500': 'CashDistribAgentAcctNumber',
    '501': 'CashDistribPayRef',
    '502': 'CashDistribAgentAcctName',
    '503': 'CardStartDate',
    '504': 'PaymentDate',
    '505': 'PaymentRemitterID',
    '506': 'RegistStatus',
    '507': 'RegistRejReasonCode',
    '508': 'RegistRefID',
    '509': 'RegistDtls',
    '510': 'NoDistribInsts',
    '511': 'RegistEmail',
    '512': 'DistribPercentage',
    '513': 'RegistID',
    '514': 'RegistTransType',
    '515': 'ExecValuationPoint',
    '516': 'OrderPercent',
    '517': 'OwnershipType',
    '518': 'NoContAmts',
    '519': 'ContAmtType',
    '520': 'ContAmtValue',
    '521': 'ContAmtCurr',
    '522': 'OwnerType',
    '523': 'PartySubID',
    '524': 'NestedPartyID',
    '525': 'NestedPartyIDSource',
    '526': 'SecondaryClOrdID',
    '527': 'SecondaryExecID',
    '528': 'OrderCapacity',
    '529': 'OrderRestrictions',
    '530': 'MassCancelRequestType',
    '531': 'MassCancelResponse',
    '532': 'MassCancelRejectReason',
    '533': 'TotalAffectedOrders',
    '534': 'NoAffectedOrders',
    '535': 'AffectedOrderID',
    '536': 'AffectedSecondaryOrderID',
    '537': 'QuoteType',
    '538': 'NestedPartyRole',
    '539': 'NoNestedPartyIDs',
    '540': 'TotalAccruedInterestAmt',
    '541': 'MaturityDate',
    '542': 'UnderlyingMaturityDate',
    '543': 'InstrRegistry',
    '544': 'CashMargin',
    '545': 'NestedPartySubID',
    '546': 'Scope',
    '547': 'MDImplicitDelete',
    '548': 'CrossID',
    '549': 'CrossType',
    '550': 'CrossPrioritization',
    '551': 'OrigCrossID',
    '552': 'NoSides',
    '553': 'Username',
    '554': 'Password',
    '555': 'NoLegs',
    '556': 'LegCurrency',
    '557': 'TotNoSecurityTypes',
    '558': 'NoSecurityTypes',
    '559': 'SecurityListRequestType',
    '560': 'SecurityRequestResult',
    '561': 'RoundLot',
    '562': 'MinTradeVol',
    '563': 'MultiLegRptTypeReq',
    '564': 'LegPositionEffect',
    '565': 'LegCoveredOrUncovered',
    '566': 'LegPrice',
    '567': 'TradSesStatusRejReason',
    '568': 'TradeRequestID',
    '569': 'TradeRequestType',
    '570': 'PreviouslyReported',
    '571': 'TradeReportID',
    '572': 'TradeReportRefID',
    '573': 'MatchStatus',
    '574': 'MatchType',
    '575': 'OddLot',
    '576': 'NoClearingInstructions',
    '577': 'ClearingInstruction',
    '578': 'TradeInputSource',
    '579': 'TradeInputDevice',
    '580': 'NoDates',
    '581': 'AccountType',
    '582': 'CustOrderCapacity',
    '583': 'ClOrdLinkID',
    '584': 'MassStatusReqID',
    '585': 'MassStatusReqType',
    '586': 'OrigOrdModTime',
    '587': 'LegSettlType',
    '588': 'LegSettlDate',
    '589': 'DayBookingInst',
    '590': 'BookingUnit',
    '591': 'PreallocMethod',
    '592': 'UnderlyingCountryOfIssue',
    '593': 'UnderlyingStateOrProvinceOfIssue',
    '594': 'UnderlyingLocaleOfIssue',
    '595': 'UnderlyingInstrRegistry',
    '596': 'LegCountryOfIssue',
    '597': 'LegStateOrProvinceOfIssue',
    '598': 'LegLocaleOfIssue',
    '599': 'LegInstrRegistry',
    '600': 'LegSymbol',
    '601': 'LegSymbolSfx',
    '602': 'LegSecurityID',
    '603': 'LegSecurityIDSource',
    '604': 'NoLegSecurityAltID',
    '605': 'LegSecurityAltID',
    '606': 'LegSecurityAltIDSource',
    '607': 'LegProduct',
    '608': 'LegCFICode',
    '609': 'LegSecurityType',
    '610': 'LegMaturityMonthYear',
    '611': 'LegMaturityDate',
    '612': 'LegStrikePrice',
    '613': 'LegOptAttribute',
    '614': 'LegContractMultiplier',
    '615': 'LegCouponRate',
    '616': 'LegSecurityExchange',
    '617': 'LegIssuer',
    '618': 'EncodedLegIssuerLen',
    '619': 'EncodedLegIssuer',
    '620': 'LegSecurityDesc',
    '621': 'EncodedLegSecurityDescLen',
    '622': 'EncodedLegSecurityDesc',
    '623': 'LegRatioQty',
    '624': 'LegSide',
    '625': 'TradingSessionSubID',
    '626': 'AllocType',
    '627': 'NoHops',
    '628': 'HopCompID',
    '629': 'HopSendingTime',
    '630': 'HopRefID',
}

# Order Status (Tag 39)
ORD_STATUS = {
    '0': 'New',
    '1': 'Partially Filled',
    '2': 'Filled',
    '3': 'Done for Day',
    '4': 'Canceled',
    '5': 'Replaced',
    '6': 'Pending Cancel',
    '7': 'Stopped',
    '8': 'Rejected',
    '9': 'Suspended',
    'A': 'Pending New',
    'B': 'Calculated',
    'C': 'Expired',
    'D': 'Accepted for Bidding',
    'E': 'Pending Replace',
}

# Order Type (Tag 40)
ORD_TYPE = {
    '1': 'Market',
    '2': 'Limit',
    '3': 'Stop',
    '4': 'Stop Limit',
    '5': 'Market on Close',
    '6': 'With or Without',
    '7': 'Limit or Better',
    '8': 'Limit with or Without',
    '9': 'On Basis',
    'A': 'On Close',
    'B': 'Limit on Close',
    'C': 'Forex Market',
    'D': 'Previously Quoted',
    'E': 'Previously Indicated',
    'F': 'Forex Limit',
    'G': 'Forex Swap',
    'H': 'Forex Previously Quoted',
    'I': 'Funari',
    'J': 'Market If Touched',
    'K': 'Market with Left Over as Limit',
    'L': 'Previous Fund Valuation Point',
    'M': 'Next Fund Valuation Point',
    'P': 'Pegged',
}

# Side (Tag 54)
SIDE = {
    '1': 'Buy',
    '2': 'Sell',
    '3': 'Buy Minus',
    '4': 'Sell Plus',
    '5': 'Sell Short',
    '6': 'Sell Short Exempt',
    '7': 'Undisclosed',
    '8': 'Cross',
    '9': 'Cross Short',
    'A': 'Cross Short Exempt',
    'B': 'As Defined',
    'C': 'Opposite',
    'D': 'Subscribe',
    'E': 'Redeem',
    'F': 'Lend',
    'G': 'Borrow',
}

# Exec Type (Tag 150)
EXEC_TYPE = {
    '0': 'New',
    '1': 'Partial Fill',
    '2': 'Fill',
    '3': 'Done for Day',
    '4': 'Canceled',
    '5': 'Replaced',
    '6': 'Pending Cancel',
    '7': 'Stopped',
    '8': 'Rejected',
    '9': 'Suspended',
    'A': 'Pending New',
    'B': 'Calculated',
    'C': 'Expired',
    'D': 'Restated',
    'E': 'Pending Replace',
    'F': 'Trade',
    'G': 'Trade Correct',
    'H': 'Trade Cancel',
    'I': 'Order Status',
}


def decode_fix(data):
    """
    Decode a FIX message from bytes.
    Returns a list of (tag_name, tag_num, value, decoded_value) tuples.
    """
    if isinstance(data, bytearray):
        data = bytes(data)
    
    # FIX uses SOH (0x01) as delimiter
    try:
        message_str = data.decode('ascii', errors='replace')
    except:
        message_str = data.decode('latin-1', errors='replace')
    
    # Replace SOH with pipe for splitting
    message_str = message_str.replace('\x01', '|')
    
    fields = message_str.strip('|').split('|')
    
    result = []
    msg_type_desc = None
    
    for field in fields:
        if '=' not in field:
            continue
        
        parts = field.split('=', 1)
        if len(parts) != 2:
            continue
            
        tag_num, value = parts
        tag_name = TAG_NAMES.get(tag_num, f'Tag{tag_num}')
        
        # Decode special values
        decoded_value = value
        if tag_num == '35':  # MsgType
            decoded_value = MESSAGE_TYPES.get(value, value)
            msg_type_desc = decoded_value
        elif tag_num == '39':  # OrdStatus
            decoded_value = ORD_STATUS.get(value, value)
        elif tag_num == '40':  # OrdType
            decoded_value = ORD_TYPE.get(value, value)
        elif tag_num == '54':  # Side
            decoded_value = SIDE.get(value, value)
        elif tag_num == '150':  # ExecType
            decoded_value = EXEC_TYPE.get(value, value)
        
        result.append((tag_name, tag_num, value, decoded_value))
    
    return result, msg_type_desc


def format_fix_message(data):
    """
    Format a FIX message for display.
    Returns a formatted string representation.
    """
    fields, msg_type_desc = decode_fix(data)
    
    if not fields:
        return "Unable to parse FIX message"
    
    output = []
    
    if msg_type_desc:
        output.append(f"=== FIX Message: {msg_type_desc} ===")
    else:
        output.append("=== FIX Message ===")
    
    for tag_name, tag_num, value, decoded_value in fields:
        if value != decoded_value:
            output.append(f"  {tag_num:>4} ({tag_name}): {value} [{decoded_value}]")
        else:
            output.append(f"  {tag_num:>4} ({tag_name}): {value}")
    
    return '\n'.join(output)
